"""The one piece of hardware you are *given*. Do not edit this file.

Everything else in this repository -- every logic gate, the ALU, the memory,
the CPU, the whole computer -- must be built from calls to `nand` and to chips
you have already built yourself.

------------------------------------------------------------------------------
SIGNAL CONVENTION
------------------------------------------------------------------------------
A single wire carries a `Bit`: the Python int 0 or the Python int 1.
Nothing else. Not `True`, not `None`, not `0.0`. `bool` is deliberately
rejected, because a `bool` in your dataflow almost always means you reached
for a Python comparison instead of building a gate.

------------------------------------------------------------------------------
BUS CONVENTION  (read this twice, it is the #1 source of bugs)
------------------------------------------------------------------------------
A multi-bit bus is a `tuple` of Bits, **least-significant bit first**:

    bus[0]  is the LSB  (value 2**0)
    bus[15] is the MSB  (value 2**15, the sign bit for 16-bit two's complement)

This matches the nand2tetris HDL, where `in[0]` is the low-order bit.
It is the *reverse* of how you write a binary numeral on paper, so the helpers
`to_bin` / `from_bin` translate to and from the paper form (MSB on the left):

    >>> from_bin("0000000000000101")      # the numeral five
    (1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
    >>> to_bin(bus(5))
    '0000000000000101'
"""

from __future__ import annotations

import contextlib
from collections.abc import Iterator, Sequence

WORD = 16  # width of the Hack machine word

#: Hardwired constant buses. A chip is allowed to tie an input pin to a fixed
#: voltage -- in the book's HDL that is written `Mux16(a=x, b=false, sel=zx)`.
#: These are the Python spelling of `false` and of a bus with only wire 0 high.
ZERO: tuple[int, ...] = (0,) * WORD
ONE: tuple[int, ...] = (1,) + (0,) * (WORD - 1)

Bit = int
Bus = tuple


class SignalError(TypeError):
    """Something that is not a clean 0/1 signal reached a chip pin."""


def check_bit(value: object, where: str = "signal") -> Bit:
    """Return `value` if it is a legal Bit, else raise SignalError."""
    if value.__class__ is bool:
        raise SignalError(
            f"{where}: got the bool {value!r}. A wire carries the int 0 or 1. "
            "A bool here usually means you used a Python comparison, `and`, "
            "`or` or `not` instead of wiring up a gate."
        )
    if value.__class__ is not int:
        raise SignalError(f"{where}: got {value!r} ({type(value).__name__}); a wire carries int 0 or 1")
    if value not in (0, 1):
        raise SignalError(f"{where}: got {value!r}; a wire carries int 0 or 1")
    return value


def check_bus(value: object, width: int = WORD, where: str = "bus") -> Bus:
    """Return `value` if it is a tuple of exactly `width` Bits, else raise."""
    if not isinstance(value, tuple):
        raise SignalError(
            f"{where}: got {type(value).__name__}; a bus is a tuple of Bits "
            "(tuple, not list -- buses are values, not mutable boxes)"
        )
    if len(value) != width:
        raise SignalError(f"{where}: got {len(value)} wires, expected {width}")
    for i, bit in enumerate(value):
        check_bit(bit, f"{where}[{i}]")
    return value


# --------------------------------------------------------------------------- #
# The primitive
# --------------------------------------------------------------------------- #

class NandCounter:
    """Counts the NAND gates burned inside a `counting()` block."""

    __slots__ = ("count",)

    def __init__(self) -> None:
        self.count = 0

    def __int__(self) -> int:
        return self.count

    def __repr__(self) -> str:
        return f"<NandCounter {self.count}>"


_active: list[NandCounter] = []
_total = 0


def nand(a: Bit, b: Bit) -> Bit:
    """NOT-AND. The single primitive gate. Output is 0 only when both inputs are 1.

        a b | out
        0 0 |  1
        0 1 |  1
        1 0 |  1
        1 1 |  0

    Physically this is four transistors: two n-channel in series pulling the
    output to ground when *both* inputs are high, and two p-channel in parallel
    pulling it to the supply otherwise. It is the cheapest useful gate there
    is, which is why we start here.
    """
    global _total
    check_bit(a, "nand input a")
    check_bit(b, "nand input b")
    _total += 1
    for counter in _active:
        counter.count += 1
    return 1 - (a * b)


@contextlib.contextmanager
def counting() -> Iterator[NandCounter]:
    """Count NAND gates used inside the block.

    >>> with counting() as c:
    ...     nand(1, 1)
    0
    >>> c.count
    1
    """
    counter = NandCounter()
    _active.append(counter)
    try:
        yield counter
    finally:
        _active.remove(counter)


def total_nands() -> int:
    """Every NAND evaluated since the process started. Mostly for fun."""
    return _total


# --------------------------------------------------------------------------- #
# Bus <-> number translation (test-harness convenience, not hardware)
# --------------------------------------------------------------------------- #

def bus(value: int, width: int = WORD) -> Bus:
    """Two's-complement bus for `value`, LSB at index 0.

    >>> bus(5, 4)
    (1, 0, 1, 0)
    >>> bus(-1, 4)
    (1, 1, 1, 1)
    """
    masked = value & ((1 << width) - 1)
    return tuple((masked >> i) & 1 for i in range(width))


def to_int(wires: Sequence[Bit], signed: bool = True) -> int:
    """Interpret a bus as a number (two's complement by default)."""
    width = len(wires)
    value = 0
    for i, bit in enumerate(wires):
        value |= bit << i
    if signed and width and wires[width - 1]:
        value -= 1 << width
    return value


def from_bin(text: str) -> Bus:
    """Parse a binary numeral written MSB-first, as in the book.

    >>> from_bin("1000")        # eight
    (0, 0, 0, 1)
    """
    cleaned = text.replace("_", "").replace(" ", "")
    if not cleaned or set(cleaned) - {"0", "1"}:
        raise ValueError(f"from_bin: {text!r} is not a binary numeral")
    return tuple(int(ch) for ch in reversed(cleaned))


def to_bin(wires: Sequence[Bit]) -> str:
    """Render a bus as a binary numeral, MSB-first (paper order).

    >>> to_bin(bus(5, 8))
    '00000101'
    """
    return "".join(str(bit) for bit in reversed(tuple(wires)))


__all__ = [
    "WORD", "ZERO", "ONE", "Bit", "Bus", "SignalError", "NandCounter",
    "nand", "counting", "total_nands",
    "check_bit", "check_bus", "bus", "to_int", "from_bin", "to_bin",
]
